config/routes.rb
Rails.application.routes.draw do
  get 'superpower/superpowers'
  get 'superhero/superheros'
  get 'author/authors'
  get 'category/categories'
  get 'welcome/index'
  get '/welcome/:id', to:'welcome#show', id: /\d+/

  resources :about

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books

  belongs_to :books

end

app/models/book.rb
class Book < ApplicationRecord
  has_many :categories
  has_one :publishers
  has_many :superheros
  has_many :authors

  belongs_to :categories
  belongs_to :publishers
  belongs_to :superheros
  belongs_to :authors

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books

  belongs_to :books

end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_one :books

  belongs_to :books

end

app/models/superhero.rb
class Superhero < ApplicationRecord
  has_many :books
  has_many :superpowers

  belongs_to :books
  belongs_to :superpowers

end

app/models/superpower.rb
class Superpower < ApplicationRecord
  has_one :superheros

  belongs_to :superheros
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def new

  end
end

app/controllers/author_controller.rb
class AuthorController < ApplicationController
  def authors
    @authors = Author.all
  end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  def categories
    @categories = Category.all
  end
end

app/controllers/superhero_controller.rb
class SuperheroController < ApplicationController
  def superheros
    @superheroes = Superhero.all
  end
end

app/controllers/superpower_controller.rb
class SuperpowerController < ApplicationController
  def superpowers
    @superpowers = Superpower.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @books = Book.all
  end

  def show
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/superhero_helper.rb
module SuperheroHelper
end

app/helpers/superpower_helper.rb
module SuperpowerHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DataProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div>
    <tr>
      <td><%= link_to 'Home', root_path %></td>
      <td><%= link_to 'Category', category_categories_path %></td>
      <td><%= link_to 'Authors', author_authors_path %></td>
      <td><%= link_to 'Superhero', superhero_superheros_path %></td>
      <td><%= link_to 'Superpower', superpower_superpowers_path %></td>
      <td><%= link_to 'About', new_about_path %></td>
    </tr>
  </div>


    <%= yield %>
  </body>
</html>